apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: archihub-backend:0.8.2
          args: ["/bin/bash", "/app/start.sh"]
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          ports:
            - containerPort: 11000
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: elasticsearch-secrets
            - secretRef:
                name: mongo-secrets
