apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
