apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        # Define the elasticsearch container
        - name: elasticsearch
          image: elasticsearch:7.17.6
          imagePullPolicy: Always
          # Define the resources for the container
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          # Define the ports for the container
          ports:
            - containerPort: 9200
            - containerPort: 9300
          # Define the environment variables for the container
          envFrom:
            - configMapRef:
                name: backend-configmap
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: elasticsearch
            - name: xpack.license.self_generated.type
              value: trial
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: http.cors.enabled
              value: "true"
            - name: http.cors.allow-origin
              value: "*"
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secrets
                  key: ELASTIC_USER
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secrets
                  key: ELASTIC_PASSWORD
          # Define the volume mounts for the container
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /var/lib/elasticsearch/data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
