apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  labels:
    app: mongodb
data:
  MONGO_INITDB_DATABASE: "archihub-prod"
  MONGO_HOST: "archihub_mongodb_server_01"
  MONGO_PORT: "27017"
