apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  labels:
    app: mongodb
data:
  MONGO_INITDB_DATABASE: "archihub-prod"
  MONGO_HOST: "mongo-svc"
  MONGO_PORT: "27017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-backup-script
data:
  backup_restore.sh: |
    #!/bin/bash
    echo "Restaurando base de datos..."

    FILES=(system.bson users.bson lists.bson forms.bson post_types.bson)

    cd /data_restore

    for file in "${FILES[@]}"
    do
        if test -f "$file"; then
            mongorestore --username $MONGO_INITDB_ROOT_USERNAME --password $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --db $MONGO_INITDB_DATABASE $file
        fi
    done

    echo "Base de datos restaurada"
