---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-certs-pvc
spec:
  accessModes:
    - ReadOnlyMany # Solo lectura
  resources:
    requests:
      storage: 1Gi # Asegúrate de que coincida con el tamaño del PV
  volumeName: elastic-certs-pv
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wait-for-pvc
spec:
  accessModes:
    - ReadOnlyMany # Solo lectura
  resources:
    requests:
      storage: 1Gi
  volumeName: wait-for-pv
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userfiles-pvc
spec:
  accessModes:
    - ReadWriteOnce # Solo lectura y escritura por un único pod
  resources:
    requests:
      storage: 5Gi # Asegúrate de que coincida con el tamaño del PV
  volumeName: userfiles-pv
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webfiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: webfiles-pv
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: uploads-pv
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: temporal-pv
  storageClassName: standard
