apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  labels:
    app: mongodb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv
  labels:
    app: mongodb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/mongo_db/backup
